server:
  port: 8060
  #swagger url:http://localhost:8060/swagger-ui.html (端口和server.port相同)

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mysql?useSSL=false&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456

#mybatis:

#  mapper-locations: classpath*:/com.chess.mapper/**.xml
 # configuration:
 #   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    schema:
      - classpath:sql/schema.sql
      - classpath:sql/data.sql
    url: jdbc:h2:mem:online-excel
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    initialization-mode: embedded  #always;embedded;never

  jpa:
    database: h2
    hibernate:
      ddl-auto: update

  #H2控制台:http://localhost:8060/h2-console
  h2:
    console:
      path: /h2-console
      enabled: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false